global:
  token: glpat-QDFAAuezMXNd9A73GXDv
  url: https://gitlab.com/
autoMergeProjects:
  - #项目名称
    token: glpat-123
    url: https://url
    name: gitlab-api-test
    #审核名称
    reviewers:
      - wangruiyu
      - ls
      - ww
    #合并MR后是否删除原分支
    removeSourceBranch: false
    #评论的内容est notes faild
    comment: check success
    #最少审核人数
    minReviewers: 1
    #检查的时间（单位：s）
    checkInterval: 3
#autoCreateMergeProjects:
#  - name: xxxx
#    source: xxxxx
#    target: xxxx
#    createTime: xxxxx
#    assignee: xxx
#    title: xxxx
#    description: xxx
#    milestone: xxx
#    reviewers:
#      - xs
#      - ls
#      - ww
#    labels:
#      - xxx
#      - xxx